# Copyright 2018 John McGehee. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM centos:latest
MAINTAINER jmcgeheeiv@users.noreply.github.com

ARG github_repo=jmcgeheeiv/pyfakefs
ARG github_branch=master

RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum install -y python3-pip unzip wget

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_COLLATE C.UTF-8

RUN useradd -u 1000 pyfakefs

RUN mkdir -p work \
    && wget https://github.com/$github_repo/archive/$github_branch.zip \
    && unzip $github_branch.zip -d work
RUN WORK_DIR=`ls -d work/*`; mv $WORK_DIR work/pyfakefs
RUN chown -R pyfakefs:pyfakefs work/pyfakefs
WORKDIR work/pyfakefs
RUN pip3 install -r requirements.txt
RUN pip3 install -r extra_requirements.txt

USER pyfakefs
ENV PYTHONPATH work/pyfakefs
ENV TEST_REAL_FS=1
CMD ["python3", "-m", "pyfakefs.tests.all_tests"]
