name: Dockertests

on:
  [push]

jobs:
  dockertests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-image: [debian, fedora, ubuntu, redhat]
    steps:
    - uses: actions/checkout@v4
    - name: Setup docker container
      run: |
        docker build -t pyfakefs -f $GITHUB_WORKSPACE/.github/workflows/dockerfiles/Dockerfile_${{ matrix.docker-image }} . --build-arg github_repo=$GITHUB_REPOSITORY --build-arg github_branch=$GITHUB_REF_NAME
    - name: Run tests
      run: docker run -t pyfakefs
